
name: Testing


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs: 
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: setup repository
        uses: actions/checkout@v3

      - name: setup deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint --unstable

      - name: Run tests
        run: deno task tst
